48-sliar-강화학습-control-변수-추가
yoon-gu/epirl pull request #58
Opened 2023-01-12 07:24 UTC by boyeon-kim

2023-01-12 11:11 UTC, boyeon-kim commented
[sliar_rl_2constraint_1st trial code]

- action : 0,1,2,3 선택 중 1개라 가정
- action : 0,1 ==> nu
- action : 2,3 ==> tau 이도록..?

우선 첫번째로 trial해봤던 코드를 업로드합니다!

2023-01-12 13:37 UTC, yoon-gu requested changes
코멘트 따라서 수정해서 돌리세요. 지금 코드는 아직 세팅 안된게 많네요.

2023-01-12 13:37 UTC, yoon-gu commented on Boyeon/dqn/sliar_rl.py
> +ACTIONS = [(0, 0),
이렇게 선언하고 `env.step( )` 의 action은 index (0, 1, 2, 3)만 사용합니다.

2023-01-12 13:37 UTC, yoon-gu commented on Boyeon/dqn/sliar_rl.py
> +            v, tau = ACTIONS[action]
이런식으로 사용하시고, 밑에 if else 문은 필요없겠네요.

2023-01-12 13:37 UTC, yoon-gu commented on Boyeon/dqn/sliar_rl.py
> +            if action == 0 or action == 1:
삭제하고 위 처럼 받아서 컨트롤 변수 2개 ode argument에 넣어주세요.

2023-01-12 13:37 UTC, yoon-gu commented on Boyeon/dqn/sliar_rl.py
> +            if action == 0 or action == 1:
71라인부터 76까지는 필요없겠네요.

2023-01-12 13:37 UTC, yoon-gu commented on Boyeon/dqn/sliar_rl.py
> +        action = 0
이 부분도 모든 컨트롤 변수가 0이므로 ACTIONS[0]이 적용되겠네요.
코드는 그대로 쓰면 되겠습니다.

2023-01-12 13:37 UTC, yoon-gu commented on Boyeon/dqn/sliar_rl.py
> +            reward = - self.P * I - self.Q * (0.01 * action1 ** 2) - self.R * (0.05 * round(action2/3,-1) ** 2)
nu_max값들은 따로 변수로 관리하세요. 이렇게 0.05로 코드 안에 고정해놓으면 나중에 고생합니다.

2023-01-12 13:37 UTC, yoon-gu commented on rl/dqn/sliar_rl.py
> +            reward = - self.P * I - self.Q * action ** 2
이 부분도 cost에 맞게 바꿔야겠네요.  nu와 tau 둘다 페널티텀이 있어야 합니다.

2023-01-12 13:42 UTC, yoon-gu commented
<img width="301" alt="image" src="https://user-images.githubusercontent.com/13851374/212082250-4144e7d2-9d75-4ff6-940e-e573074650e9.png">

`sliar_rl.py` 가 2개인데 실제 사용하는건 뭔가요?

2023-01-12 14:36 UTC, boyeon-kim commented
episode 2000번 : 

![SLIAR_control_u](https://user-images.githubusercontent.com/69612871/212094747-5db3bee4-c9f8-4653-86ac-5f89e36baba4.png)
![SLIAR_w_control](https://user-images.githubusercontent.com/69612871/212094767-75a2d386-1349-4d79-aedd-eb8b12d64692.png)

2023-01-13 00:59 UTC, yoon-gu commented
뭔가 파일들이 꼬여있네요. 오늘 세미나 끝나고 한번 같이 봐요.

2023-01-13 14:44 UTC, yoon-gu approved these changes

2023-01-13 14:44 UTC, merged