84 dqn 수정된 알고리즘 업로드
yoon-gu/epirl pull request #88
Opened 2023-02-21 14:21 UTC by Rabbit739

2023-02-21 15:46 UTC, yoon-gu requested changes
코드 돌아가지 않습니다. 고쳐서 올려주세요.

2023-02-23 13:17 UTC, yoon-gu commented
이거 안돌아가는거 빠르게 대응 부탁해요. 이게 Merge 되어야 보연이 일을 할 수가 있어서..

2023-02-23 13:51 UTC, Rabbit739 commented
conf 파일에 빠져있던 변수 추가해서 돌아가는 것 확인했습니다!

2023-02-24 11:55 UTC, yoon-gu approved these changes

2023-02-24 11:55 UTC, merged